# ./filebeat/filebeat.yml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs_from_host/*.log # Đường dẫn bên trong container Filebeat
  json.keys_under_root: true
  json.add_error_key: true
  # tags: ["from-docker-filebeat"]

processors:
  - add_host_metadata: ~ # Thêm thông tin host của Filebeat (có thể không cần thiết nếu log đã có service_name)
  - add_cloud_metadata: ~

output.kafka:
  hosts: ["kafka:9092"] # "kafka" là tên service Kafka trong docker-compose
  topic: 'application-logs'
  required_acks: 1
  compression: gzip
  # (Nếu Kafka có bảo mật, cần cấu hình thêm)
  # username: "your_kafka_user"
  # password: "your_kafka_password"

# logging.level: debug # Để debug Filebeat