spring:
  cloud:
    gateway:
      routes:
        - id: cart-route
          uri: http://localhost:6062
          predicates:
            - Path=/api/cart/**, /api/cart

        - id: product-route
          uri: http://localhost:6061
          predicates:
            - Path=/api/movie/**, /api/movie

        - id: user-route
          uri: http://localhost:6060
          predicates:
            - Path=/api/auth/**, /api/user, /api/user/**

        - id: order-route
          uri: http://localhost:6063
          predicates:
            - Path=/api/order/**
app:
  security:
    public-endpoints:
      - /api/auth/**
