spring:
  cloud:
    gateway:
      routes:
        - id: cart-route
          uri: http://localhost:6062
          predicates:
            - Path=/api/cart/**, /api/cart

        - id: product-route
          uri: http://localhost:6061
          predicates:
            - Path=/api/admin/product/**, /api/admin/product,
              /api/seller/product/**, /api/seller/product,
              /api/product/**, /api/product,
              /api/admin/category/**, /api/admin/category,
              /api/category/**, /api/category

        - id: user-route
          uri: http://localhost:6060
          predicates:
            - Path=/api/auth/**, /api/user, /api/user/**

        - id: order-route
          uri: http://localhost:6063
          predicates:
            - Path=/api/order/**, /api/order/, 
              /api/admin/**, /api/admin/
app:
  security:
    public-endpoints:
      - /api/auth/**
      - /api/product/**
      - /api/product
