spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      default-binder: rabbit
      bindings:
        paymentSuccess-out-0:
          destination: payment-success
          group: payment-success-group
        paymentFail-out-0:
          destination: payment-fail
          group: payment-fail-group