spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    function:
      definition: paymentSuccess;paymentFail;stockUpdateSuccess;stockUpdateFail;clearCartSuccess
    stream:
      default-binder: rabbit
      bindings:
        stockUpdate-out-0:
          destination: stock-update
          group: stock-update-group
        clearCart-out-0:
          destination: clear-cart
          group: clear-cart-group
        sendConfirmOrderMail-out-0:
          destination: send-confirmOrderMail
          group: send-confirmMail-group
        sendUpdateOrderMail-out-0:
          destination: send-updateOrderMail
          group: send-updateMail-group
        sendToGetFullConfirmOrder-out-0:
          destination: send-ToGetFullConfirmOrder
          group: send-ToGetFullConfirmOrder-group
        paymentSuccess-in-0:
          destination: payment-success
          group: payment-success-group
        paymentFail-in-0:
          destination: payment-fail
          group: payment-fail-group
        stockUpdateSuccess-in-0:
          destination: stockUpdate-success
          group: stockUpdate-success-group
        stockUpdateFail-in-0:
          destination: stockUpdate-fail
          group: stockUpdate-fail-group
        clearCartSuccess-in-0:
          destination: clearCart-success
          group: clearCart-success-group