spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      default-binder: rabbit
      bindings:
        stockUpdate-out-0:
          destination: stock-update
          group: stock-update-group
        clearCart-out-0:
          destination: clear-cart
          group: clear-cart-group
        sendConfirmOrderMail-out-0:
          destination: send-confirmOrderMail
          group: send-confirmMail-group
        sendUpdateOrderMail-out-0:
          destination: send-updateOrderMail
          group: send-updateMail-group