spring:
  cloud:
    function:
      definition: stockUpdate
    stream:
      default-binder: rabbit
      bindings:
        stockUpdate-in-0:
          destination: stock-update
          group: stock-update-group
        stockUpdateSuccess-out-0:
          destination: stockUpdate-success
          group: stockUpdate-success-group
        stockUpdateFail-out-0:
          destination: stockUpdate-fail
          group: stockUpdate-fail-group
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin