spring:
  cloud:
    function:
      definition: stockUpdate;updateAverageRatingAdd;updateAverageRatingDelete
    stream:
      default-binder: rabbit
      bindings:
        stockUpdate-in-0:
          destination: stock-update
          group: stock-update-group
        stockUpdateSuccess-out-0:
          destination: stockUpdate-success
          group: stockUpdate-success-group
        stockUpdateFail-out-0:
          destination: stockUpdate-fail
          group: stockUpdate-fail-group
        updateAverageRatingAdd-in-0:
          destination: update-AverageRatingAdd
          group: update-AverageRatingAdd-group
        updateAverageRatingDelete-in-0:
          destination: update-AverageRatingDelete
          group: update-AverageRatingDelete-group

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin